project:
  type: website
  output-dir: "docs"

website:
  title: "EidÖ WiSe22"
  navbar:
    left:
      - href: Vorlesung.qmd
        text: "Vorlesung"
      - href: uebung.qmd
        text: "Übung"
    right:
      - icon: github
        href: https://github.com/mca91
        aria-label: GitHub
      - icon: git
        href: https://github.com/mca91/Eidoe22
        aria-label: GitHub
  page-footer:
    center: "Content by Martin Arnold. Built using <a href='https://quarto.org'>Quarto</a> &centerdot; Licensed under <a href='https://creativecommons.org/licenses/by-sa/4.0/'>CC BY-SA 4.0</a>"
  open-graph: true
  
format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

