project:
  type: website
  output-dir: "docs"

website:
  title: "EidÖ WiSe22"
  navbar:
    left:
      - href: Vorlesung.qmd
        text: "Vorlesung"
      - href: uebung.qmd
        text: "Übung"
  page-footer:
    center: 
      - text: "Content by Martin Arnold"
        href: " "
      - text: "Licensed under CC BY-SA 4.0"
        href: "https://creativecommons.org/licenses/by-sa/4.0/"
  
format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

