project:
  type: website
  output-dir: "docs"

website:
  title: "EidÖ WiSe22"
  navbar:
    left:
      - href: Vorlesung.qmd
        text: "Vorlesung"
      - href: uebung.qmd
        text: "Übung"
  page-footer:
    center: "Written by Martin Arnold using <a href='https://quarto.org'>Quarto</a> &centerdot; Licensed under <a href='https://creativecommons.org/licenses/by-sa/4.0/'>CC BY-SA 4.0</a>"

  
format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

