---
title: "Übung"
---

Nachfolgend finden Sie Materialien für die Übung. Die Veranstaltung findet -- vorbehaltlich weiterer Entwicklungen -- weiterhin in R11 T08 C98 statt.

Bei wichtigen Fragen bzgl. der Übung wenden Sie sich bitte per Email an [Martin Arnold](mailto:martchriarno@googlemail.com?subject=[EidÖ]).

## Online-Companion (ITER)

[Link zum Online-Companion](https://www.econometrics-with-r.org/)

## Übungsblätter

- [Übungsblatt 1](https://github.com/mca91/Eidoe22/raw/main/Blatt-1.pdf)
- [Übungsblatt 2](https://github.com/mca91/Eidoe22/raw/main/Blatt-2.pdf)
- [Übungsblatt 3](https://github.com/mca91/Eidoe22/raw/main/Blatt-3.pdf)
- [Übungsblatt 4](https://github.com/mca91/Eidoe22/raw/main/Blatt-4.pdf)
- [Übungsblatt 5](https://github.com/mca91/Eidoe22/raw/main/Blatt-5.pdf)
- [Übungsblatt 6](https://github.com/mca91/Eidoe22/raw/main/Blatt-6.pdf)
- [Übungsblatt 7](https://github.com/mca91/Eidoe22/raw/main/Blatt-7.pdf)

## R-Lösungen

- [R-Funktionssammlung](https://github.com/mca91/Eidoe22/raw/main/rfunktionen.pdf) (kein Anspruch auf Vollständigkeit!)
- [R-Lösungen Blatt 1](https://github.com/mca91/Eidoe22/raw/main/Blatt-1_R_sol.pdf)
- [R-Lösungen Blatt 3](https://github.com/mca91/Eidoe22/raw/main/Blatt-3_R_sol.pdf)
- [R-Lösungen Blatt 4](https://github.com/mca91/Eidoe22/raw/main/Blatt-4_R_sol.pdf)

### R-Pakete

[Hinweise zur Installation von R-Paketen](https://github.com/mca91/Eidoe22/raw/main/R-Pakete.pdf)

## Sonstige Lösungen

- [Blatt 4 A4](https://github.com/mca91/Eidoe22/raw/main/Blatt-4-A4.pdf)

## Datensätze

- [CASchools.Rdata](https://github.com/mca91/Eidoe22/raw/main/CASchools.Rdata)
- [br.dat](https://github.com/mca91/Eidoe22/raw/main/br.dat) (Rechtsklick &#8594; Ziel/Datei speichern als/unter, falls sich kein download öffnet)
- [br.def](https://github.com/mca91/Eidoe22/raw/main/br.def)
- [Boston](https://github.com/mca91/Eidoe22/raw/main/Boston.Rdata)

## Zusatzaufgabe 1

**<span style=color:#ff9c00;>Bitte beachten Sie, dass die Deadline für Einreichungen zu Zusatzaufgabe 1 aufgrund der aktuellen Situation bis einschließlich 21.12.2022 verlängert wurde!<span/>**

*Mit dieser Zusatzaufgabe können Sie bis zu 2.5 Zusatzpunkte für die Klausur erwerben. Die Zusatzpunkte werden nur bei bestandener Klausur angerechnet. Sie können die Aufgaben in einer Gruppe von bis zu drei Personen bearbeiten. Ihre Lösungen sind bis einschließlich Mittwoch, den 21.12.2022, unter Nennung von Namen und Matrikelnummer aller Beteiligten als kommentiertes R-Skript per E-Mail an [Martin Arnold](mailto:martchriarno@googlemail.com?subject=[EidÖ]) einzureichen.*

- [Zusatzaufgabe 1](https://github.com/mca91/Eidoe22/raw/main/Assignment1.pdf)
- <a href="https://github.com/mca91/Eidoe22/raw/main/stimmung.csv" download>stimmung.csv</a> (Rechtsklick &#8594; Ziel/Datei speichern als/unter, falls sich kein download öffnet)


## Optionales Kursangebot bei DataCamp

Über [diesen Link](https://www.datacamp.com/groups/shared_links/6be1aaf777a4eae948e83c8b536cbe96a8f7021b962abe18026275f5082f3697) gelangen Sie zu unserer DataCamp-Gruppe. Bitte kontaktieren Sie den Übungsleiter bzgl. Freischaltung.

